src/EasySurvey.Web/ViewModels/AnswerGroup/AnswerGroupViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EasySurvey.Common.Models;

namespace EasySurvey.Web.ViewModels.AnswerGroup
{
    public class AnswerGroupViewModel
    {        

        public AnswerGroupViewModel(Common.Models.AnswerGroup answerGroup)
        {
            Id = answerGroup.Id;
            IsUsed = answerGroup.IsUsed;
            SectionGroupId = answerGroup.SectionGroupId;
            SurveyId = answerGroup.SurveyId;
            SectionGroupTitle = answerGroup.SectionGroup.Title;
            IsMandatory = answerGroup.SectionGroup.IsMandatory;
        }

        public int Id { get; set; }    
        public bool IsUsed { get; set; }
        public bool IsMandatory { get; set; }
        public int SectionGroupId { get; set; }
        public int SurveyId { get; set; }
        public string SectionGroupTitle { get; set; }
    }
}

src/EasySurvey.Web/ViewModels/AnswerGroups/AnswerGroupListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EasySurvey.Web.ViewModels.AnswerGroups
{
    public class AnswerGroupListViewModel
    {
        public int SurveyId { get; set; }
        public ICollection<AnswerGroupViewModel> AnswerGroupViewModel { get; set; }
        public int SelectedId { get; set; }
    }
}

src/EasySurvey.Web/ViewModels/AnswerGroups/AnswerGroupSelectViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EasySurvey.Web.ViewModels.AnswerGroups
{
    public class AnswerGroupSelectViewModel
    {
        public int SurveyId { get; set; }
        public int SectionGroupId { get; set; }
        public AnswerGroupsViewModel AnswerGroupsViewModel { get; set; }
        public AnswerGroupSelectViewModel()
        {
            AnswerGroupsViewModel = new AnswerGroupsViewModel();
        }
    }
}

src/EasySurvey.Web/ViewModels/AnswerGroups/AnswerGroupViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EasySurvey.Common.Models;
using EasySurvey.Web.ViewModels.AnswerSections;
using System.ComponentModel.DataAnnotations;
using System.Collections;

namespace EasySurvey.Web.ViewModels.AnswerGroups
{
    public class AnswerGroupViewModel
    {
        public AnswerGroupViewModel()
        {
        }

        public AnswerGroupViewModel(Common.Models.AnswerGroup answerGroup)
        {
            Id = answerGroup.Id;
            SectionGroupId = answerGroup.SectionGroupId;
            SurveyId = answerGroup.SurveyId;
            Title = answerGroup.SectionGroup.Title;
            IsMandatory = answerGroup.SectionGroup.IsMandatory;
            IsUsed = answerGroup.IsUsed;
            SortOrder = answerGroup.SortOrder;

            if (answerGroup.AddressId.HasValue && answerGroup.Address != null)
            {
                AddressId = answerGroup.Address.Id;
                Recipient = answerGroup.Address.Recipient;
                AddressLine1 = answerGroup.Address.AddressLine1;
                PostalCode = answerGroup.Address.PostalCode;
                City = answerGroup.Address.City;
                Country = answerGroup.Address.Country;
            }

            SectionGroup = answerGroup.SectionGroup;
            AnswerSection = new AnswerSectionsViewModel();
            foreach (var answerSection in answerGroup.AnswerSection.OrderBy(item=>item.Order))
            {
                AnswerSection.Add(new AnswerSectionViewModel(answerSection));
            }
        }

        public int Id { get; set; }
        public int SectionGroupId { get; set; }
        public int SurveyId { get; set; }
        public string Title { get; set; }
        public bool IsMandatory { get; set; }
        [Display(Name = "Wish to fill this area")]
        public bool IsUsed { get; set; }

        // Address Fields
        public int AddressId { get; set; }
        public string Recipient { get; set; }
        public string AddressLine1 { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public int SortOrder { get; set; }
        public SectionGroup SectionGroup { get; set; }
        public virtual AnswerSectionsViewModel AnswerSection { get; set; }
    }

    
}

src/EasySurvey.Web/ViewModels/AnswerGroups/AnswerGroupsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EasySurvey.Web.ViewModels.AnswerGroups
{
    public class AnswerGroupsViewModel : List<AnswerGroupViewModel>
    {
        public AnswerGroupsViewModel() : base()
        {
        }
    }
}

src/EasySurvey.Web/Controllers/AnswerGroupsController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using EasySurvey.Common.Models;
using EasySurvey.Web.Models;
using EasySurvey.Web.ViewModels.AnswerGroups;
using EasySurvey.Services.ServiceDefinitions;
using System.Collections.Generic;
using System;

namespace EasySurvey.Web.Controllers
{
    public class AnswerGroupsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IAnswerGroupService _answerGroupService;
        private readonly ISectionGroupService _sectionGroupService;

        public AnswerGroupsController(ApplicationDbContext context
            , IAnswerGroupService answerGroupService
            , ISectionGroupService sectionGroupService)
        {
            _context = context;
            _answerGroupService = answerGroupService;
            _sectionGroupService = sectionGroupService;
        }

        // GET: AnswerGroups
        public IActionResult Index(int? id, int selected = 0)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            List<AnswerGroupViewModel> listModels = new List<AnswerGroupViewModel>();
            var answerGroups = _answerGroupService.GetBySurveyId(id.Value);
            answerGroups.OrderBy(item=> item.SectionGroup.SortOrder).ToList().ForEach(item => listModels.Add(new AnswerGroupViewModel(item)));

            AnswerGroupListViewModel listModel = new AnswerGroupListViewModel();
            listModel.SurveyId = id.Value;
            listModel.AnswerGroupViewModel = listModels;
            listModel.SelectedId = selected > 0 ? selected : listModels.First().SectionGroupId;
            return View(listModel);
        }

        // GET: AnswerGroups/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            AnswerGroup answerGroup = _context.AnswerGroup.Single(m => m.Id == id);
            if (answerGroup == null)
            {
                return HttpNotFound();
            }

            return View(answerGroup);
        }

        // GET: AnswerGroups/Create
        public IActionResult Create()
        {
            ViewData["SectionGroupId"] = new SelectList(_context.SectionGroup, "Id", "SectionGroup");
            ViewData["SurveyId"] = new SelectList(_context.Survey, "Id", "Survey");
            return View();
        }

        // POST: AnswerGroups/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(AnswerGroup answerGroup)
        {
            if (ModelState.IsValid)
            {
                _context.AnswerGroup.Add(answerGroup);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewData["SectionGroupId"] = new SelectList(_context.SectionGroup, "Id", "SectionGroup", answerGroup.SectionGroupId);
            ViewData["SurveyId"] = new SelectList(_context.Survey, "Id", "Survey", answerGroup.SurveyId);
            return View(answerGroup);
        }

        // GET: AnswerGroups/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
                return HttpNotFound();

            var answerGroup = _answerGroupService.GetById(id.Value);
            if (answerGroup == null)
                return HttpNotFound();

            AnswerGroupViewModel editAnswerGroupViewModel = new AnswerGroupViewModel(answerGroup);
            return View(editAnswerGroupViewModel);
        }

        [HttpGet]
        public IActionResult EditAjax(int id)
        {
            var answerGroup = _answerGroupService.GetById(id);
            if (answerGroup == null)
                return HttpNotFound();
            AnswerGroupViewModel editAnswerGroupViewModel = new AnswerGroupViewModel(answerGroup);
            return PartialView(@"_EditAnswerGroup", editAnswerGroupViewModel);
        }

        [HttpGet]
        public IActionResult EditAnswerGroupsAjax(int surveyId, int sectionGroupId)
        {
            try
            {
                var answerGroups = _answerGroupService.GetBySurveyAndSectionGroupId(surveyId, sectionGroupId);
                if (answerGroups == null)
                    return HttpNotFound();
                AnswerGroupSelectViewModel selectViewModel = new AnswerGroupSelectViewModel() { SurveyId = surveyId, SectionGroupId = sectionGroupId };
                foreach (var answerGroup in answerGroups)
                    selectViewModel.AnswerGroupsViewModel.Add(new AnswerGroupViewModel(answerGroup));
                return PartialView(@"_EditAnswerGroups", selectViewModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }   
            
        }

        // POST: AnswerGroups/Edit/5
        [HttpPost("Edit")]
        //[ValidateAntiForgeryToken]
        public IActionResult Edit(AnswerGroupSelectViewModel selectViewModel, string command)
        {
            foreach (var answerGroup in selectViewModel.AnswerGroupsViewModel)
            {
                var existingAnswerGroup = _answerGroupService.GetById(answerGroup.Id);
                if (existingAnswerGroup != null)
                {
                    if (existingAnswerGroup.Address == null)
                        existingAnswerGroup.Address = new Address();
                    existingAnswerGroup.Address.AddressLine1 = answerGroup.AddressLine1;
                    existingAnswerGroup.Address.PostalCode = answerGroup.PostalCode;
                    existingAnswerGroup.Address.City = answerGroup.City;
                    existingAnswerGroup.Address.Country = answerGroup.Country;

                    foreach (var answerSection in answerGroup.AnswerSection)
                    {
                        AnswerSection existingAnswerSection = existingAnswerGroup.AnswerSection.Where(item => item.Id == answerSection.Id).FirstOrDefault();
                        if (existingAnswerSection != null)
                        {
                            foreach (var answer in answerSection.Answer)
                            {
                                Answer existingAnswer = existingAnswerSection.Answer.Where(item => item.Id == answer.Id).FirstOrDefault();
                                existingAnswer.AnswerText = answer.AnswerText;
                                existingAnswer.DefaultComments = answer.Comments;
                                existingAnswer.OptionId = answer.OptionId;
                            }
                        }
                    }
                    _answerGroupService.Save(existingAnswerGroup);
                }
            }

            switch (command)
            {
                case "Save":
                        break;
                case "Extend":
                    AnswerGroupViewModel result = selectViewModel.AnswerGroupsViewModel.OrderBy(item => item.SortOrder).FirstOrDefault();
                    var existingAnswerGroup = _answerGroupService.GetById(result.Id);
                    _answerGroupService.Extend(existingAnswerGroup);
                    break;
            }

            if (ModelState.IsValid)
            {
                return RedirectToAction("Index", new { id = selectViewModel.SurveyId, selected = selectViewModel.SectionGroupId });
            }
            return RedirectToAction("Index", new { id = selectViewModel.SurveyId, selected = selectViewModel.SectionGroupId });
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public IActionResult ExtendAjax([FromBody]AnswerGroupViewModel answerGroup)
        {
            if (ModelState.IsValid)
            {
                var toUpdate = _answerGroupService.GetById(answerGroup.Id);
                var result = _answerGroupService.Extend(toUpdate);
                return RedirectToAction("Index", new { id = answerGroup.SurveyId, selected = answerGroup.SectionGroupId });
            }
            ViewData["SectionGroupId"] = new SelectList(_context.SectionGroup, "Id", "SectionGroup", answerGroup.SectionGroupId);
            ViewData["SurveyId"] = new SelectList(_context.Survey, "Id", "Survey", answerGroup.SurveyId);
            return RedirectToAction("Index", new { id = answerGroup.SurveyId, selected = answerGroup.SectionGroupId });
        }

        // POST: AnswerGroups/Edit/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public IActionResult EditAjax([FromBody]AnswerGroupViewModel answerGroup)
        {
            var toUpdate = _answerGroupService.GetById(answerGroup.Id);
            toUpdate.IsUsed = answerGroup.IsUsed;
            var result = _answerGroupService.Save(toUpdate);

            var answerGroups = _answerGroupService.GetBySurveyAndSectionGroupId(answerGroup.SurveyId, answerGroup.SectionGroupId);
            if (answerGroups == null)
                return HttpNotFound();
            AnswerGroupSelectViewModel selectViewModel = new AnswerGroupSelectViewModel() { SurveyId = answerGroup.SurveyId, SectionGroupId = answerGroup.SectionGroupId };
            foreach (var answerGroupUpdated in answerGroups)
                selectViewModel.AnswerGroupsViewModel.Add(new AnswerGroupViewModel(answerGroupUpdated));
            return PartialView(@"_EditAnswerGroups", selectViewModel);
        }

        // GET: AnswerGroups/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var answerGroup = _answerGroupService.GetById(id.Value);
            if (answerGroup == null)
            {
                return HttpNotFound();
            }

            var result = _answerGroupService.DeleteById(id.Value);
            return RedirectToAction("Index", new { id = answerGroup.SurveyId });
        }

src/EasySurvey.Web/Views/AnswerGroups/Create.cshtml
@model EasySurvey.Common.Models.AnswerGroup

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>AnswerGroup</h4>
        <hr />
        <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="CreatedBy" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CreatedBy" class="form-control" />
                <span asp-validation-for="CreatedBy" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CreatedOn" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CreatedOn" class="form-control" />
                <span asp-validation-for="CreatedOn" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="checkbox">
                    <input asp-for="IsUsed" />
                    <label asp-for="IsUsed"></label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ModifiedBy" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ModifiedBy" class="form-control" />
                <span asp-validation-for="ModifiedBy" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ModifiedOn" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ModifiedOn" class="form-control" />
                <span asp-validation-for="ModifiedOn" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="SectionGroupId" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="SectionGroupId" class ="form-control"></select>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="SurveyId" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="SurveyId" class ="form-control"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

</body>
</html>

src/EasySurvey.Web/Views/AnswerGroups/Delete.cshtml
@model EasySurvey.Common.Models.AnswerGroup

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AnswerGroup</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsUsed)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsUsed)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ModifiedOn)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModifiedOn)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>
</body>
</html>

src/EasySurvey.Web/Views/AnswerGroups/Details.cshtml
@model EasySurvey.Common.Models.AnswerGroup

@{
    Layout = null;
}

<<div class="section_group row panel panel-default">
    @{
        var titleCssId = "title_bar_section_group" + Model.Id;
        var insideCssId = "inside_section_group" + Model.Id;
    }
    <div id="@titleCssId" class="title_bar_section_group panel-heading">
        <h4 class="panel-title">
            <a data-toggle="collapse" data-target="#@insideCssId">
                @{
                    @Html.HiddenFor(model => model.SectionGroup.IsMandatory)

                    if (Model.SectionGroup.IsMandatory)
                    {
                        @Html.LabelFor(m => m.SectionGroup.IsMandatory, " *", new { @class = "red" })
                    }
                    @Html.LabelFor(model => model.SectionGroup.Title, Model.SectionGroup.Title, new { Class = "left" })
                }
            </a>
        </h4>

    </div>
    <div id="@insideCssId" class="inside_section_group panel-collapse collapse in">
        @foreach (var section in Model.SectionGroup.Section.OrderBy(item => item.SortOrder))
        {
            await Html.RenderPartialAsync("~/views/Sections/_ViewSection.cshtml", section, ViewData);
        }
    </div>
</div>

src/EasySurvey.Web/Views/AnswerGroups/Edit.cshtml
@model EasySurvey.Web.ViewModels.AnswerGroups.EditAnswerGroupViewModel
<div class="section_group row panel panel-default">
    @{
        var titleCssId = "title_bar_section_group" + Model.Id;
        var insideCssId = "inside_section_group" + Model.Id;
    }
    <div id="@titleCssId" class="title_bar_section_group panel-heading">
        <h4 class="panel-title">
            <a data-toggle="collapse" data-target="#@insideCssId">
                @{
                    @Html.HiddenFor(model => model.SectionGroup.IsMandatory)

                    if (Model.SectionGroup.IsMandatory)
                    {
                        @Html.LabelFor(m => m.SectionGroup.IsMandatory, " *", new { @class = "red" })
                    }
                    @Html.LabelFor(model => model.SectionGroup.Title, Model.SectionGroup.Title, new { Class = "left" })
                }
            </a>
        </h4>

    </div>
    <div id="@insideCssId" class="inside_section_group panel-collapse collapse in">
        @foreach (var section in Model.SectionGroup.Section.OrderBy(item => item.SortOrder))
        {
            await Html.RenderPartialAsync("~/views/Sections/_EditSection.cshtml", section, ViewData);
        }
    </div>
</div>

src/EasySurvey.Web/Views/AnswerGroups/_EditAnswerGroup.cshtml
@model EasySurvey.Web.ViewModels.AnswerGroups.AnswerGroupViewModel
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="AddressId" />
    <input type="hidden" asp-for="IsMandatory" />
    @{
        if (Model.IsUsed)
        {
            <div id="justified-button-bar" class="col-lg-12">
                <div class="btn-group btn-group-justified">
                    <div class="btn-group">
                        <button id="btnValidate" name="command" title="Validate the current answer group" type="submit" class="btn btn-default" value="Validate">
                            <span class="glyphicon glyphicon-check"></span>&nbsp; Validate
                        </button>
                    </div>
                    <div class="btn-group">
                        <button id="btnSave" name="command" title="Save the current answer group" type="submit" class="btn btn-default" value="Save">
                            <span class="glyphicon glyphicon-floppy-disk"></span>&nbsp; Save
                        </button>
                    </div>
                    <div class="btn-group">
                        <button id="button-map" name="command" title="Add set of repeative sections to answer group" type="submit" class="btn btn-default" value="Extend">
                            <span class="glyphicon glyphicon-plus"></span>&nbsp; Extend
                        </button>
                    </div>
                    <div class="btn-group">
                        <button id="btnComment" title="Enter and edit comments" type="button" class="btn btn-default" data-toggle="modal" data-target="#commentModel">
                            <span class="glyphicon glyphicon-eye-open"></span>&nbsp; Comments
                        </button>
                    </div>
                </div>
            </div>
            <br />
            <br />
            @Html.EditorFor(model => model)               
        }
    }
    <div class="modal fade" id="commentModel" tabindex="-1" role="dialog" aria-labelledby="commentModelLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="commentModelLabel">Add Comment</h4>
                </div>
                <div class="modal-body">
                    <div class="col-sm-offset-1">
                        <div class="form-group">
                            <label id="optionName" class="control-label">Comment*</label>
                            <textarea type="text" id="commentText" rows="6" class="form-control input-lg col-xs-6" style="min-width: 90%" />
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <a id="submit1" name="submit1" href="#" class="btn btn-primary">Add</a>
                </div>
            </div>
        </div>
    </div>

src/EasySurvey.Web/Views/AnswerGroups/_EditAnswerGroups.cshtml
@model EasySurvey.Web.ViewModels.AnswerGroups.AnswerGroupSelectViewModel

<form id="answergroup-form" asp-controller="AnswerGroups" asp-action="Edit" method="post" asp-anti-forgery="true">
    <input type="hidden" asp-for="SectionGroupId" />
    <input type="hidden" asp-for="SurveyId" />
    @{
        var mainModel = Model.AnswerGroupsViewModel.First();
        if (mainModel != null && mainModel.IsUsed)
        {
            <div id="justified-button-bar" class="col-lg-12">
                <div class="btn-group btn-group-justified">
                    <div class="btn-group">
                        <button id="btnValidate" name="command" title="Validate the current answer group" type="submit" class="btn btn-default" value="Validate">
                            <span class="glyphicon glyphicon-check"></span>&nbsp; Validate
                        </button>
                    </div>
                    <div class="btn-group">
                        <button id="btnSave" name="command" title="Save the current answer group" type="submit" class="btn btn-default" value="Save">
                            <span class="glyphicon glyphicon-floppy-disk"></span>&nbsp; Save
                        </button>
                    </div>
                    <div class="btn-group">
                        <button id="button-map" name="command" title="Add set of repeative sections to answer group" type="submit" class="btn btn-default" value="Extend">
                            <span class="glyphicon glyphicon-plus"></span>&nbsp; Extend
                        </button>
                    </div>
                    <div class="btn-group">
                        <button id="btnComment" title="Enter and edit comments" type="button" class="btn btn-default" data-toggle="modal" data-target="#commentModel">
                            <span class="glyphicon glyphicon-eye-open"></span>&nbsp; Comments
                        </button>
                    </div>
                </div>
            </div>
            <br />
            <br />
            @Html.EditorFor(model => Model.AnswerGroupsViewModel);
        }
    }
</form>
<div class="modal fade" id="commentModel" tabindex="-1" role="dialog" aria-labelledby="commentModelLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="commentModelLabel">Add Comment</h4>
            </div>
            <div class="modal-body">
                <div class="col-sm-offset-1">
                    <div class="form-group">
                        <label id="optionName" class="control-label">Comment*</label>
                        <textarea type="text" id="commentText" rows="6" class="form-control input-lg col-xs-6" style="min-width: 90%" />
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <a id="submit1" name="submit1" href="#" class="btn btn-primary">Add</a>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

<script src="~/js/Comments/CommentsAjaxModule.js" asp-append-version="true"></script>

<script type="text/javascript">
    $(document)
        .ready(function () {
            $('a[name="submit1"]')
                .click(function (event) {
                    var name = $('#commentText').val();
                    var surveyId = $('input#SurveyId').val();
                    CommentsAjax.addComment(name, surveyId);
                    $('#commentModel').modal('toggle');
                });
        });
</script>